volumes:
  postgres_data:

services:
  postgres-database:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=credentials_registration
    volumes:
      - postgres_data:/var/lib/postgresql/data
  java-service:
    image: credentials-registration:1.0
    ports:
      - "8080:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-database:5432/credentials_registration
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
    depends_on:
      - postgres-database
